# SPDX-FileCopyrightText: 2015-2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

"""`bits brew` — generate a Homebrew Brewfile from the recipes.

macOS is a developer platform for bits (it does not build/distribute CVMFS
packages there), so stable, low-level system libraries are sourced from Homebrew
rather than built. A recipe opts in by declaring, in its YAML header:

    homebrew_formula: readline          # one formula, or a list
    homebrew_taps:                      # optional, rarely needed
      - some/tap

This command scans the recipe directory, collects every such declaration that
applies to the target architecture (its prefer_system must match, when present),
and writes a Brewfile — the executable manifest of the macOS "system layer".
Install it in one shot with `brew bundle --file Brewfile`, or let
`bits build --brew` install formulae on demand during resolution.

The Brewfile is a *derived* artifact: the recipes are the source of truth. Keep
it next to them in the recipe repo (e.g. lcg.bits/macos/Brewfile) and regenerate
+ commit whenever a recipe's Homebrew declaration changes. `--check` (CI / pre-
commit) fails if the committed file is stale.
"""

import os
import sys
import glob

from bits_helpers.log import debug, error, info
from bits_helpers.recipe import parseRecipe, FileReader


def _as_list(value):
  """Normalise a scalar-or-list YAML value into a list of strings."""
  if value is None:
    return []
  if isinstance(value, (list, tuple)):
    return [str(v).strip() for v in value if str(v).strip()]
  return [str(value).strip()] if str(value).strip() else []


# Formulae the bits BUILD SYSTEM itself needs on macOS, independent of any recipe.
# gnu-tar (gtar): deterministic package tarballs — build_template.sh uses GNU tar's
# --sort/--mtime so packages are byte-identical across nodes (finding R1). Always
# emitted so it can never fall out of the Brewfile when recipes change.
BASE_FORMULAE = frozenset({"gnu-tar"})


def collect_homebrew(configDir, architecture):
  """Return (formulae, taps) declared by recipes in configDir for architecture.

  The Brewfile is a macOS artifact (Homebrew is the macOS system layer here), so
  for a non-osx architecture there is nothing to emit. On osx, the build-system
  base formulae (BASE_FORMULAE) are always included, and a recipe contributes its
  `homebrew_formula` when it declares no `prefer_system` (author opted in
  unconditionally) or its `prefer_system` regex matches `architecture` (so a
  Linux-only declaration is never emitted into a macOS Brewfile).
  """
  import re
  formulae, taps = set(), set()
  if not str(architecture).startswith("osx"):
    return formulae, taps
  formulae |= BASE_FORMULAE
  for path in sorted(glob.glob(os.path.join(configDir, "*.sh"))):
    err, spec, _ = parseRecipe(FileReader(path))
    if err or not spec:
      # Not a parseable recipe (e.g. a defaults-*.sh helper). Skip quietly.
      continue
    declared = _as_list(spec.get("homebrew_formula"))
    if not declared:
      continue
    pref = spec.get("prefer_system")
    if pref is not None:
      try:
        if not re.match(pref, architecture):
          continue
      except re.error:
        error("brew: malformed prefer_system %r in %s", pref, os.path.basename(path))
        continue
    formulae.update(declared)
    taps.update(_as_list(spec.get("homebrew_taps")))
  return formulae, taps


def render_brewfile(formulae, taps, architecture):
  """Render a sorted, deterministic Brewfile string."""
  lines = [
    "# Generated by `bits brew` — do not edit by hand.",
    "# Source of truth: the homebrew_formula: fields in the bits recipes, plus the",
    "# build-system base tools (gnu-tar, for reproducible package tarballs).",
    "# Regenerate with:  bits brew -a %s -o <this file>" % architecture,
    "# Install with:     brew bundle --file <this file>",
    "",
  ]
  for tap in sorted(taps):
    lines.append('tap "%s"' % tap)
  if taps:
    lines.append("")
  for formula in sorted(formulae):
    lines.append('brew "%s"' % formula)
  return "\n".join(lines) + "\n"


def doBrew(args, parser):
  """Entry point for `bits brew`."""
  if not str(args.architecture).startswith("osx"):
    info("brew: architecture %s is not macOS; the Brewfile will list only "
         "recipes whose prefer_system matches it (usually none).", args.architecture)

  if not os.path.isdir(args.configDir):
    parser.error("config directory not found: %s" % args.configDir)

  # The Brewfile is a derived artifact of the recipes, so by default it lives
  # next to them at <configDir>/macos/Brewfile (e.g. lcg.bits/macos/Brewfile).
  if args.output is None:
    args.output = os.path.join(args.configDir, "macos", "Brewfile")

  formulae, taps = collect_homebrew(args.configDir, args.architecture)
  content = render_brewfile(formulae, taps, args.architecture)

  if args.check:
    # CI / pre-commit: succeed only if the file already matches.
    if args.output == "-":
      parser.error("--check needs a real --output file, not stdout")
    try:
      with open(args.output) as fh:
        current = fh.read()
    except OSError:
      error("brew: %s is missing; run 'bits brew -o %s' to create it.",
            args.output, args.output)
      return False
    if current != content:
      error("brew: %s is out of date; regenerate with 'bits brew -o %s'.",
            args.output, args.output)
      return False
    info("brew: %s is up to date (%d formulae).", args.output, len(formulae))
    return True

  if args.output == "-":
    sys.stdout.write(content)
  else:
    out_dir = os.path.dirname(os.path.abspath(args.output))
    if out_dir and not os.path.isdir(out_dir):
      os.makedirs(out_dir, exist_ok=True)
    with open(args.output, "w") as fh:
      fh.write(content)
    info("brew: wrote %d formulae%s to %s", len(formulae),
         (" and %d taps" % len(taps)) if taps else "", args.output)
  return True
