# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

"""Per-release NOTICE / attribution and GPL source-offer generation.

Permissive licences require retaining copyright/attribution notices, and
GPL/LGPL binaries may only be distributed with the corresponding source made
available. The build manifest already records every package's SPDX ``license``
(hash-excluded recipe metadata) and its source archives' store paths, so both
obligations can be discharged mechanically at publish time:

  * ``NOTICE`` — one file per release: required attribution texts (only for
    the packages actually present), every distributed package with its SPDX
    licence id, and the list of packages EXCLUDED from distribution because
    their licence forbids it (``redistributable: sources|none``).

  * ``LICENSE-SOURCE-OFFER.txt`` — the written offer for the copyleft (GPL
    family) components: where the corresponding source archives are available
    and for how long. Packages whose SOURCES are not redistributable are never
    listed (and a copyleft package in that state is contradictory — flagged).

Both are generated from the manifest alone (no network), uploaded next to the
release's BOMs under ``MANIFESTS/<build_id>/`` by the bulk publish, and placed
at the root of a published release view. Everything here is best-effort: a
NOTICE failure must never fail a publish.

This is the per-RELEASE aggregation; it complements the per-PACKAGE ``NOTICE``
that the build script already writes into each ``$INSTALLROOT`` from the same
recipe metadata (``build.py`` ``_notice_block``), whose copyleft detection
(:func:`bits_helpers.build._is_copyleft`) is reused here so the two can never
disagree about what needs a source offer.
"""

import datetime
import os

from bits_helpers.log import debug, info, warning
from bits_helpers.sync import redistributable_forms

# Attribution texts required by specific licences, keyed by bits package name
# (lower-case). Only emitted when the package is actually in the release.
ATTRIBUTIONS = {
    "cfitsio":   "This product includes CFITSIO software developed by "
                 "NASA/HEASARC.",
    "geant4":    "This product includes software developed by Members of the "
                 "Geant4 Collaboration (http://cern.ch/geant4).",
    "jpeg":      "This software is based in part on the work of the "
                 "Independent JPEG Group.",
    "madx":      "MAD-X: Copyright CERN. Distributed under the MIT licence; "
                 "the CERN copyright notice is retained.",
    "photoscpp": "PHOTOS++: Copyright the PHOTOS++ authors. Distributed under "
                 "the MIT licence; the copyright notice is retained.",
}

SOURCE_OFFER_YEARS = 3


def _distributed(entries):
    """Manifest entries that are actually part of a binary distribution."""
    out = []
    for e in entries or []:
        pkg = str(e.get("package", ""))
        if not pkg or pkg.startswith("defaults"):
            continue
        if "binaries" in redistributable_forms(e.get("redistributable")):
            out.append(e)
    return out


def _excluded(entries):
    """Entries excluded from distribution by their licence."""
    return [e for e in entries or []
            if str(e.get("package", "")) and
            not str(e.get("package", "")).startswith("defaults") and
            "binaries" not in redistributable_forms(e.get("redistributable"))]


def _is_copyleft(license_id):
    # Single source of truth, shared with the per-package NOTICE writer:
    # handles LGPL/AGPL/MPL and "… WITH <exception>" ids, not just "GPL".
    from bits_helpers.build import _is_copyleft as _impl
    return _impl(license_id)


def generate_notice(entries, build_id="unknown") -> str:
    """Return the NOTICE text for a release described by manifest *entries*."""
    dist = sorted(_distributed(entries), key=lambda e: str(e.get("package", "")).lower())
    excl = sorted(_excluded(entries), key=lambda e: str(e.get("package", "")).lower())
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    lines = [
        "NOTICE — third-party software attributions",
        "Release: %s" % build_id,
        "Generated by bits publish on %s from the release build manifest." % now,
        "",
        "This distribution contains third-party software under the licences",
        "listed below (SPDX identifiers). Licence texts: https://spdx.org/licenses/",
        "",
    ]
    seen = {str(e.get("package", "")).lower() for e in dist}
    attrib = [ATTRIBUTIONS[p] for p in sorted(ATTRIBUTIONS) if p in seen]
    if attrib:
        lines += ["Required attributions:", ""]
        lines += ["  * %s" % a for a in attrib]
        lines.append("")
    lines += ["Packages:", ""]
    for e in dist:
        lines.append("  %-30s %-18s %s" % (e.get("package"),
                                           e.get("version", "?"),
                                           e.get("license") or "NOASSERTION"))
    if excl:
        lines += ["", "Not included in this distribution (licence forbids "
                      "redistribution; obtain upstream):", ""]
        lines += ["  %-30s %s" % (e.get("package"), e.get("license") or "")
                  for e in excl]
    return "\n".join(lines) + "\n"


def generate_source_offer(entries, store_url=None, build_id="unknown") -> str:
    """Return the written source offer for the release's copyleft components."""
    now = datetime.datetime.now(datetime.timezone.utc)
    until = now.replace(year=now.year + SOURCE_OFFER_YEARS)
    lines = [
        "LICENSE-SOURCE-OFFER — corresponding source",
        "Release: %s" % build_id,
        "",
        "For every GPL/LGPL-licensed component distributed in this release,",
        "the complete corresponding source code is available at the archive",
        "locations below%s until at least %s." % (
            (" under %s" % store_url.rstrip("/")) if store_url else
            " in the bits source store", until.strftime("%Y-%m-%d")),
        "",
    ]
    for e in sorted(_distributed(entries),
                    key=lambda e: str(e.get("package", "")).lower()):
        lic = e.get("license") or ""
        if not _is_copyleft(lic):
            continue
        if "sources" not in redistributable_forms(e.get("redistributable")):
            # Contradiction: copyleft binaries whose sources may not be
            # shared cannot be distributed compliantly at all.
            warning("source-offer: %s is %s but its sources are not "
                    "redistributable — review its recipe flags",
                    e.get("package"), lic)
            continue
        lines.append("%s %s (%s):" % (e.get("package"), e.get("version", "?"), lic))
        paths = [s.get("store_path") for s in e.get("source_checksums") or []
                 if isinstance(s, dict) and s.get("store_path")]
        commit = e.get("commit_hash")
        for p in paths:
            lines.append("  %s" % p)
        if not paths and commit:
            lines.append("  git checkout of commit %s" % commit)
        elif not paths:
            lines.append("  (source location not recorded — request from the "
                         "release maintainers)")
        lines.append("")
    return "\n".join(lines) + "\n"


def upload_release_compliance(s3, bucket, build_id, entries, store_url=None):
    """Upload NOTICE + LICENSE-SOURCE-OFFER.txt next to the release's BOMs.

    Best-effort: never raises, never fails the publish.
    """
    try:
        for name, body in (("NOTICE", generate_notice(entries, build_id)),
                           ("LICENSE-SOURCE-OFFER.txt",
                            generate_source_offer(entries, store_url, build_id))):
            key = "MANIFESTS/%s/%s" % (build_id, name)
            s3.put_object(Bucket=bucket, Key=key, Body=body.encode("utf-8"))
            info("compliance file -> %s/%s", bucket, key)
        return True
    except Exception as exc:              # pylint: disable=broad-except
        warning("could not upload the NOTICE/source-offer files: %s", exc)
        return False


def write_release_compliance(dirpath, entries, build_id, store_url=None):
    """Write NOTICE + LICENSE-SOURCE-OFFER.txt into *dirpath* (a release/view
    root). Best-effort: returns True when both files were written."""
    try:
        for name, body in (("NOTICE", generate_notice(entries, build_id)),
                           ("LICENSE-SOURCE-OFFER.txt",
                            generate_source_offer(entries, store_url, build_id))):
            with open(os.path.join(dirpath, name), "w", encoding="utf-8") as fh:
                fh.write(body)
        debug("compliance files written to %s", dirpath)
        return True
    except Exception as exc:              # pylint: disable=broad-except
        warning("could not write the NOTICE/source-offer files to %s: %s",
                dirpath, exc)
        return False
